export type ToolIconKind =
  | "photo-resize"
  | "image-compress"
  | "video-compress"
  | "document-photo"
  | "photo-signature-joiner"
  | "print-sheet"
  | "jpg-to-pdf"
  | "pdf-compress"
  | "pdf-merge-split"
  | "print-job-slip"
  | "quick-send"
  | "image-format-convert"
  | "qr-generate"
  | "qr-scan"
  | "heic-to-jpg"
  | "photo-grayscale"
  | "aadhaar-collage"
  | "image-to-text"
  | "pdf-to-jpg"
  | "pdf-rotate"
  | "signature-maker"
  | "image-crop"
  | "image-rotate"
  | "bg-remove"
  | "batch-compress"
  | "aadhaar-mask"
  | "pdf-password"
  | "pdf-page-manager"
  | "pdf-page-numbers"
  | "pdf-watermark"
  | "pdf-redact"
  | "pdf-sign"
  | "pdf-unlock"
  | "pdf-crop"
  | "pdf-flatten"
  | "pdf-ocr"
  | "scan-to-pdf"
  | "pdf-form-filler"
  | "image-watermark"
  | "image-resize"
  | "text-to-pdf"
  | "pdf-repair"
  | "gst-invoice"
  | "salary-slip"
  | "affidavit"
  | "rent-agreement"
  | "zip-tool"
  | "pdf-to-images"
  | "pdf-metadata"
  | "image-to-base64"
  | "image-color-picker"
  | "experience-letter"
  | "noc-generator"
  | "bonafide-certificate"
  | "cheque-print"
  | "emi-calculator"
  | "unit-converter"
  | "word-counter"
  | "barcode-generator"
  | "svg-to-png"
  | "svg-viewer"
  | "contrast-checker"
  | "color-convert"
  | "color-palette"
  | "palette-builder"
  | "gradient-maker"
  | "shadow-maker"
  | "border-radius-tool"
  | "favicon-maker"
  | "social-image-resize"
  | "placeholder-img"
  | "css-unit-converter"
  | "business-card-maker";

export type ToolCategory = "forms" | "sharing" | "utility";

export interface ToolCategoryDef {
  id: ToolCategory;
  label: string;
  description?: string;
}

export const toolCategories: ToolCategoryDef[] = [
  { id: "forms", label: "Sarkari forms" },
  { id: "sharing", label: "Sharing & print shop" },
  { id: "utility", label: "Quick utilities" },
];

// --- Spec-aligned taxonomy (base-infrastructure-plan §1.1) ----------------

export type ToolType =
  | "resize-to-spec"
  | "compress-to-target"
  | "convert"
  | "compose"
  | "extract"
  | "generate"
  | "transfer"
  | "enhance"
  | "pipeline";

export type ToolBuildStatus = "shipped" | "next" | "later" | "skip";

// Domain taxonomy used by search, sitemap, and segment ranking. Distinct from
// `category` (the UI grouping in the homepage tool grid).
export type ToolDomain = "image" | "video" | "pdf" | "sarkari" | "ocr" | "qr" | "utility";

export type Paywall = "always-free" | "batch-gated" | "high-cost";

export type WasmDep = "pdfjs" | "qpdf" | "onnx" | "heic" | "tesseract";

export type Segment =
  | "operator"
  | "professional"
  | "individual-paying"
  | "aspirant"
  | "unknown";

export interface ToolVariants {
  param: string;
  values: string[];
}

export interface Tool {
  // --- existing fields (UI-facing; do not break) --------------------------
  slug: string;
  href: string;
  name: string;
  tagline: string;
  description: string;
  status: "live" | "soon";
  category: ToolCategory;
  iconKind: ToolIconKind;
  iconColor: "accent" | "info" | "success" | "warning" | "error" | "neutral";

  // --- spec fields (base-infrastructure-plan §1.1) ------------------------
  type: ToolType;
  buildStatus: ToolBuildStatus;
  domain: ToolDomain;
  paywall: Paywall;

  // discovery
  keywords: string[];
  popularityScore?: number;

  // segment ranking
  segmentAffinity?: Partial<Record<Segment, number>>;

  // engineering
  inputAccept: string[];
  needsWorker: boolean;
  needsWasm?: WasmDep[];
  decodedPixelCap?: number;

  // routing
  variants?: ToolVariants;

  // cross-tool ("Continue Editing" pipeline targets)
  nextSteps?: string[];

  // i18n (optional; tools migrate to dictionary keys progressively)
  nameKey?: string;
  taglineKey?: string;
  descriptionKey?: string;
}

const IMAGE_ACCEPT = ["image/jpeg", "image/png", "image/webp", "image/heic", "image/heif"];

export const tools: Tool[] = [
  {
    slug: "photo-resize",
    href: "/photo-resize",
    name: "Exam Photo Resizer",
    tagline: "UPSC, SSC, NEET, JEE - exact pixel + KB specs",
    description:
      "Upload a photo, pick the exam, and get a portal-ready JPG with the right pixel size, KB target and white background.",
    status: "live",
    category: "forms",
    iconKind: "photo-resize",
    iconColor: "accent",
    type: "resize-to-spec",
    buildStatus: "shipped",
    domain: "image",
    paywall: "always-free",
    keywords: [
      "photo resize", "exam photo", "passport photo", "photo size", "resize photo",
      "photo ka size", "photo banaye", "foto resize", "exam ka photo", "photo theek karo",
      "फोटो रिसाइज़", "परीक्षा फोटो", "पासपोर्ट फोटो",
      "upsc photo", "ssc photo", "neet photo", "ibps photo", "jee photo", "railway photo",
      "rrb photo", "sbi photo", "bank po photo", "state psc photo", "police photo",
      "20kb photo", "50kb photo", "100kb photo", "200kb photo", "300kb photo",
    ],
    inputAccept: IMAGE_ACCEPT,
    needsWorker: false,
    decodedPixelCap: 16_000_000,
    variants: {
      param: "exam",
      values: ["upsc", "ssc", "neet", "ibps", "railway", "jee", "state-psc", "police", "sbi"],
    },
    nextSteps: ["photo-signature-joiner", "print-sheet", "image-compress"],
  },
  {
    slug: "image-compress",
    href: "/image-compress",
    name: "Image Compressor",
    tagline: "Hit an exact KB target",
    description:
      "Compress any image to a precise KB size - 20 KB, 50 KB, 200 KB or any custom target. Within ±5 KB of your goal.",
    status: "live",
    category: "forms",
    iconKind: "image-compress",
    iconColor: "info",
    type: "compress-to-target",
    buildStatus: "shipped",
    domain: "image",
    paywall: "always-free",
    keywords: [
      "image compressor", "compress image", "reduce photo size", "shrink image", "photo size reducer",
      "photo ka size kam karna", "photo chota karo", "foto compress", "image size kam", "photo size ghatao",
      "photo chhota", "photo chotta", "image kam karo", "photo light",
      "इमेज कम्प्रेस", "फोटो साइज़ कम", "फोटो छोटा",
      "10kb", "20kb", "50kb", "100kb", "200kb", "500kb",
      "10kb photo", "20kb photo", "50kb photo", "100kb photo", "200kb photo",
      "photo under 50kb", "photo under 100kb", "kb photo",
      "ssc photo size", "ibps 50kb", "neet 200kb photo",
    ],
    inputAccept: IMAGE_ACCEPT,
    needsWorker: false,
    decodedPixelCap: 16_000_000,
    variants: {
      param: "size",
      values: ["10kb", "20kb", "50kb", "100kb", "200kb", "500kb"],
    },
    nextSteps: ["jpg-to-pdf", "photo-signature-joiner"],
  },
  {
    slug: "video-compress",
    href: "/video-compress",
    name: "Video Compressor",
    tagline: "Hit an exact MB target",
    description:
      "Compress any video to under a target size - 10 MB, 25 MB, 50 MB or any custom target. Runs entirely in your browser, nothing uploaded.",
    status: "live",
    category: "sharing",
    iconKind: "video-compress",
    iconColor: "info",
    type: "compress-to-target",
    buildStatus: "shipped",
    domain: "video",
    paywall: "always-free",
    keywords: [
      "video compressor", "compress video", "reduce video size", "shrink video", "video size reducer",
      "video ka size kam karna", "video chota karo", "video compress karo", "video size ghatao",
      "वीडियो कम्प्रेस", "वीडियो साइज़ कम",
      "10mb video", "25mb video", "50mb video", "100mb video",
      "whatsapp video size", "email video attachment size", "video under 25mb", "video under 16mb",
    ],
    inputAccept: ["video/mp4", "video/webm", "video/quicktime", "video/x-matroska"],
    needsWorker: true,
    variants: {
      param: "size",
      values: ["10mb", "25mb", "50mb", "100mb"],
    },
    nextSteps: ["quick-send"],
  },
  {
    slug: "document-photo",
    href: "/document-photo",
    name: "Document Photo Maker",
    tagline: "Aadhaar, PAN, Passport, OCI, Voter ID",
    description:
      "Identity-document photos at exact spec - dimensions, KB and white background. Ready for the portal.",
    status: "live",
    category: "forms",
    iconKind: "document-photo",
    iconColor: "success",
    type: "enhance",
    buildStatus: "shipped",
    domain: "image",
    paywall: "high-cost",
    keywords: [
      "document photo", "id photo", "aadhaar photo", "pan photo", "passport photo", "voter id photo",
      "oci photo", "white background photo", "background remove", "background hatao",
      "aadhar photo", "adhar photo", "passport size", "id ka photo",
      "photo background white karo", "background change",
      "आधार फोटो", "पैन फोटो", "पासपोर्ट साइज़", "सफेद बैकग्राउंड",
      "uidai photo", "aadhaar update photo", "pan card photo",
    ],
    inputAccept: IMAGE_ACCEPT,
    needsWorker: false,
    needsWasm: ["onnx"],
    decodedPixelCap: 6_000_000,
    variants: {
      param: "document",
      values: ["aadhaar", "pan", "passport", "voter-id", "oci"],
    },
    nextSteps: ["photo-signature-joiner", "print-sheet", "image-compress"],
  },
  {
    slug: "photo-signature-joiner",
    href: "/photo-signature-joiner",
    name: "Photo + Signature Joiner",
    tagline: "Combine for SSC and IBPS uploads",
    description:
      "Merge a photo and signature into a single image at portal-standard dimensions. Side-by-side or stacked.",
    status: "live",
    category: "forms",
    iconKind: "photo-signature-joiner",
    iconColor: "warning",
    type: "compose",
    buildStatus: "shipped",
    domain: "sarkari",
    paywall: "always-free",
    keywords: [
      "photo signature joiner", "signature photo combine", "join photo signature",
      "photo aur signature", "signature jodna", "photo signature merge",
      "signature photo banaye", "form ke liye photo signature",
      "फोटो साइन जोड़ो", "हस्ताक्षर फोटो", "सिग्नेचर फोटो",
      "ssc signature", "ibps signature", "bank exam signature",
    ],
    inputAccept: IMAGE_ACCEPT,
    needsWorker: false,
    nextSteps: ["print-sheet", "jpg-to-pdf"],
  },
  {
    slug: "print-sheet",
    href: "/print-sheet",
    name: "Print Sheet Generator",
    tagline: "6–8 passport photos on one sheet",
    description:
      "Lay out passport-size photos on a 4×6 inch or A4 sheet with cutting guides. Print at home or any studio.",
    status: "live",
    category: "forms",
    iconKind: "print-sheet",
    iconColor: "neutral",
    type: "compose",
    buildStatus: "shipped",
    domain: "image",
    paywall: "always-free",
    keywords: [
      "print sheet", "passport photo sheet", "print photos", "photo print layout",
      "ek sheet par photo", "passport size print", "photo a4 par",
      "print ke liye photo", "studio photo sheet",
      "प्रिंट शीट", "पासपोर्ट फोटो प्रिंट", "ए4 पर फोटो",
      "4x6 photo", "a4 photo sheet",
    ],
    inputAccept: ["image/jpeg", "image/png"],
    needsWorker: false,
    segmentAffinity: { operator: 0.9, professional: 0.4 },
    nextSteps: ["jpg-to-pdf"],
  },
  {
    slug: "jpg-to-pdf",
    href: "/jpg-to-pdf",
    name: "JPG / Image to PDF",
    tagline: "Combine images into one PDF",
    description:
      "Stitch one or many images into a PDF, reorder pages, rotate as needed. A4 or Letter, portrait or landscape.",
    status: "live",
    category: "forms",
    iconKind: "jpg-to-pdf",
    iconColor: "error",
    type: "convert",
    buildStatus: "shipped",
    domain: "pdf",
    paywall: "always-free",
    keywords: [
      "jpg to pdf", "image to pdf", "photo to pdf", "convert jpg pdf", "png to pdf",
      "jpg ko pdf banao", "photo se pdf", "image se pdf banaye", "pdf banao photo se",
      "jpg pdf kaise banaye", "ek pdf me photo",
      "जेपीजी पीडीएफ", "फोटो से पीडीएफ", "इमेज पीडीएफ",
      "documents to pdf", "scan to pdf",
    ],
    inputAccept: ["image/jpeg", "image/png", "image/webp"],
    needsWorker: false,
    popularityScore: 0.9,
    nextSteps: ["pdf-compress", "pdf-merge-split"],
  },
  {
    slug: "pdf-compress",
    href: "/pdf-compress",
    name: "PDF Compressor",
    tagline: "Shrink PDFs to fit the upload limit",
    description:
      "Re-encodes embedded photos and strips metadata to hit form-portal upload limits. Light, recommended or stronger - your call.",
    status: "live",
    category: "forms",
    iconKind: "pdf-compress",
    iconColor: "info",
    type: "compress-to-target",
    buildStatus: "shipped",
    domain: "pdf",
    paywall: "always-free",
    keywords: [
      "pdf compressor", "compress pdf", "reduce pdf size", "shrink pdf", "pdf size reducer",
      "pdf ka size kam karo", "pdf chota karo", "pdf kam karo", "pdf size ghatao",
      "पीडीएफ कम्प्रेस", "पीडीएफ साइज़ कम", "पीडीएफ छोटा",
      "pdf under 100kb", "pdf under 500kb", "pdf 1mb",
    ],
    inputAccept: ["application/pdf"],
    needsWorker: true,
    needsWasm: ["pdfjs"],
    popularityScore: 0.95,
    nextSteps: ["pdf-merge-split"],
  },
  {
    slug: "pdf-merge-split",
    href: "/pdf-merge-split",
    name: "PDF Merge & Split",
    tagline: "Combine PDFs or split by page ranges",
    description:
      "Merge several PDFs into one, or split a PDF into separate files using page ranges like '1-3, 5, 7-9'. All in-browser.",
    status: "live",
    category: "forms",
    iconKind: "pdf-merge-split",
    iconColor: "accent",
    type: "compose",
    buildStatus: "shipped",
    domain: "pdf",
    paywall: "always-free",
    keywords: [
      "pdf merge", "merge pdf", "combine pdf", "join pdf", "pdf split", "split pdf",
      "pdf ko jodo", "pdf alag karo", "pdf jodna", "pdf todo", "pdf milao",
      "do pdf ek karo", "pdf pages alag",
      "पीडीएफ मर्ज", "पीडीएफ जोड़ो", "पीडीएफ अलग",
      "merge and split pdf", "pdf pages extract",
    ],
    inputAccept: ["application/pdf"],
    needsWorker: true,
    needsWasm: ["pdfjs"],
    popularityScore: 0.9,
    nextSteps: ["pdf-compress"],
  },
  {
    slug: "pdf-to-jpg",
    href: "/pdf-to-jpg",
    name: "PDF to JPG Converter",
    tagline: "Every page as its own image",
    description:
      "Turn each page of a PDF into a JPG or PNG at 72, 150 or 300 DPI. Download one page or all of them.",
    status: "live",
    category: "forms",
    iconKind: "pdf-to-jpg",
    iconColor: "warning",
    type: "convert",
    buildStatus: "shipped",
    domain: "pdf",
    paywall: "always-free",
    keywords: [
      "pdf to jpg", "pdf to image", "pdf to png", "convert pdf to jpg", "pdf page to image",
      "extract images from pdf", "pdf ko jpg banao", "pdf se photo", "pdf image convert",
      "पीडीएफ से जेपीजी", "पीडीएफ को इमेज",
      "pdf to picture", "pdf screenshot", "pdf page export",
    ],
    inputAccept: ["application/pdf"],
    needsWorker: true,
    needsWasm: ["pdfjs"],
    popularityScore: 0.85,
    nextSteps: ["image-compress", "photo-resize", "image-crop"],
  },
  {
    slug: "pdf-rotate",
    href: "/pdf-rotate",
    name: "PDF Page Rotator",
    tagline: "Fix sideways pages without re-scanning",
    description:
      "Turn one page or every page by 90°, 180° or 270° and save. Page content is copied untouched, so nothing is re-encoded.",
    status: "live",
    category: "forms",
    iconKind: "pdf-rotate",
    iconColor: "info",
    type: "enhance",
    buildStatus: "shipped",
    domain: "pdf",
    paywall: "always-free",
    keywords: [
      "rotate pdf", "pdf rotate", "turn pdf page", "pdf sideways", "fix pdf orientation",
      "pdf ghumao", "pdf seedha karo", "pdf page ghumana",
      "पीडीएफ घुमाओ", "पीडीएफ सीधा",
      "rotate pdf pages online", "pdf upside down",
    ],
    inputAccept: ["application/pdf"],
    needsWorker: true,
    needsWasm: ["pdfjs"],
    nextSteps: ["pdf-compress", "pdf-merge-split", "pdf-to-jpg"],
  },
  {
    slug: "signature-maker",
    href: "/signature-maker",
    name: "Signature Maker",
    tagline: "Draw a signature, download the image",
    description:
      "Sign on screen with a finger, stylus or mouse and download a transparent PNG or white-background JPG, trimmed to the ink. No scanner needed.",
    status: "live",
    category: "forms",
    iconKind: "signature-maker",
    iconColor: "accent",
    type: "generate",
    buildStatus: "shipped",
    domain: "sarkari",
    paywall: "always-free",
    keywords: [
      "signature maker", "draw signature", "signature online", "digital signature image",
      "signature png", "transparent signature", "signature banao", "hastakshar",
      "sign kaise banaye", "signature image banao",
      "हस्ताक्षर", "सिग्नेचर बनाओ",
      "signature for form", "signature upload", "signature without scanner",
    ],
    inputAccept: [],
    needsWorker: false,
    popularityScore: 0.6,
    nextSteps: ["image-compress", "photo-signature-joiner"],
  },
  {
    slug: "image-crop",
    href: "/image-crop",
    name: "Image Cropper",
    tagline: "Free crop, or locked to a ratio",
    description:
      "Crop a photo freehand or lock it to 1:1, 4:3, 3:4, 16:9 or the 3.5:4.5 passport proportion. PNG and WebP keep transparency.",
    status: "live",
    category: "utility",
    iconKind: "image-crop",
    iconColor: "success",
    type: "enhance",
    buildStatus: "shipped",
    domain: "image",
    paywall: "always-free",
    keywords: [
      "crop image", "image crop", "photo crop", "crop photo online", "cut image",
      "photo kaato", "photo crop karo", "image kaatna", "foto crop",
      "फोटो क्रॉप", "इमेज काटो",
      "square crop", "passport crop", "aspect ratio crop", "trim image",
    ],
    inputAccept: IMAGE_ACCEPT,
    needsWorker: false,
    decodedPixelCap: 16_000_000,
    popularityScore: 0.75,
    nextSteps: ["image-compress", "photo-resize", "jpg-to-pdf"],
  },
  {
    slug: "image-rotate",
    href: "/image-rotate",
    name: "Image Rotate & Flip",
    tagline: "Turn or mirror a photo, permanently",
    description:
      "Rotate by 90°, 180° or 270° and mirror left–right or top–bottom. The orientation is written into the pixels, so portals that ignore EXIF still show it right.",
    status: "live",
    category: "utility",
    iconKind: "image-rotate",
    iconColor: "neutral",
    type: "enhance",
    buildStatus: "shipped",
    domain: "image",
    paywall: "always-free",
    keywords: [
      "rotate image", "flip image", "image rotate", "photo rotate", "mirror image",
      "photo ghumao", "photo seedha karo", "photo palto", "image ghumana",
      "फोटो घुमाओ", "इमेज पलटो",
      "rotate photo online", "photo sideways fix", "exif orientation",
    ],
    inputAccept: IMAGE_ACCEPT,
    needsWorker: false,
    decodedPixelCap: 16_000_000,
    nextSteps: ["image-crop", "image-compress", "jpg-to-pdf"],
  },
  {
    slug: "print-job-slip",
    href: "/print-job-slip",
    name: "Print Job Slip",
    tagline: "Bundle files with shop-ready instructions",
    description:
      "Pick files, set copies, color or B&W, sides and page ranges. Outputs one PDF starting with a cover sheet the print shop can read at a glance.",
    status: "live",
    category: "sharing",
    iconKind: "print-job-slip",
    iconColor: "warning",
    type: "generate",
    buildStatus: "shipped",
    domain: "utility",
    paywall: "always-free",
    keywords: [
      "print job slip", "print shop", "print order", "print instructions",
      "print shop ke liye", "print ka order", "xerox shop",
      "प्रिंट जॉब", "प्रिंट ऑर्डर",
      "cover sheet print", "print specifications",
    ],
    inputAccept: ["application/pdf", "image/jpeg", "image/png"],
    needsWorker: false,
    segmentAffinity: { operator: 0.8 },
  },
  {
    slug: "image-format-convert",
    href: "/image-format-convert",
    name: "Image Format Converter",
    tagline: "JPG ↔ PNG ↔ WebP, in your browser",
    description:
      "Convert between JPG, PNG and WebP. JPG flattens transparency to white for portal compatibility.",
    status: "live",
    category: "forms",
    iconKind: "image-format-convert",
    iconColor: "info",
    type: "convert",
    buildStatus: "shipped",
    domain: "image",
    paywall: "always-free",
    keywords: [
      "image converter", "jpg to png", "png to jpg", "webp to jpg", "jpg to webp",
      "image format change", "convert image", "image convert", "jpeg to png",
      "इमेज कन्वर्ट", "फोटो फॉर्मेट",
      "format converter", "any to jpg", "any to png",
    ],
    inputAccept: IMAGE_ACCEPT,
    needsWorker: false,
    decodedPixelCap: 16_000_000,
    nextSteps: ["image-compress", "jpg-to-pdf", "photo-signature-joiner"],
  },
  {
    slug: "qr-generate",
    href: "/qr-generate",
    name: "QR Code Generator",
    tagline: "Make a QR for a URL, UPI ID or contact",
    description:
      "Type the text and get a clean, downloadable QR code. Works for URLs, UPI IDs, phone numbers, plain text. PNG download.",
    status: "live",
    category: "utility",
    iconKind: "qr-generate",
    iconColor: "accent",
    type: "generate",
    buildStatus: "shipped",
    domain: "qr",
    paywall: "always-free",
    keywords: [
      "qr code generator", "make qr code", "qr code banao", "upi qr code",
      "url qr", "phone number qr", "qr banaye",
      "क्यूआर कोड", "क्यूआर बनाओ", "यूपीआई क्यूआर",
      "create qr", "generate qr", "qr code free",
    ],
    inputAccept: [],
    needsWorker: false,
    popularityScore: 0.85,
  },
  {
    slug: "qr-scan",
    href: "/qr-scan",
    name: "QR Code Scanner",
    tagline: "Scan a QR with your camera or from an image",
    description:
      "Decode any QR (UPI, URL, phone, plain text) using your camera or by dropping an image. Runs entirely in your browser.",
    status: "live",
    category: "utility",
    iconKind: "qr-scan",
    iconColor: "info",
    type: "extract",
    buildStatus: "shipped",
    domain: "qr",
    paywall: "always-free",
    keywords: [
      "qr code scanner", "scan qr code", "qr scanner", "scan qr", "qr decode",
      "qr code read", "qr padhna", "qr scan karo", "qr code scan online",
      "scan qr from image", "qr code reader",
      "क्यूआर स्कैनर", "क्यूआर स्कैन", "क्यूआर पढ़ो",
      "upi qr scan", "url qr scan", "qr code dekho",
    ],
    inputAccept: ["image/jpeg", "image/png", "image/webp"],
    needsWorker: false,
    popularityScore: 0.75,
  },
  {
    slug: "image-to-text",
    href: "/image-to-text",
    name: "Image to Text (OCR)",
    tagline: "Extract typed text from a photo or scan",
    description:
      "Pull selectable, copyable text out of an image: screenshots, scanned pages, notices. Supports English and Hindi. Runs on your device, nothing uploaded.",
    status: "live",
    category: "utility",
    iconKind: "image-to-text",
    iconColor: "accent",
    type: "extract",
    buildStatus: "shipped",
    domain: "ocr",
    paywall: "always-free",
    keywords: [
      "image to text", "photo to text", "ocr", "extract text from image", "text from photo",
      "picture to text", "screenshot to text", "scan to text", "read text from image",
      "photo se text", "image se text nikalo", "text kaise nikale", "photo ka text",
      "इमेज से टेक्स्ट", "फोटो से टेक्स्ट", "ओसीआर", "टेक्स्ट निकालो",
      "hindi ocr", "english ocr", "copy text from image", "image text extractor",
      "handwriting to text", "document to text", "notice text extract",
    ],
    inputAccept: ["image/jpeg", "image/png", "image/webp"],
    needsWorker: true,
    needsWasm: ["tesseract"],
    decodedPixelCap: 16_000_000,
    popularityScore: 0.65,
    nextSteps: ["jpg-to-pdf"],
  },
  {
    slug: "heic-to-jpg",
    href: "/heic-to-jpg",
    name: "HEIC to JPG Converter",
    tagline: "Turn iPhone HEIC photos into upload-ready JPG",
    description:
      "Indian government portals reject HEIC. Drop an iPhone photo here, get a JPG in seconds. Works on any browser. No upload, no app.",
    status: "live",
    category: "forms",
    iconKind: "heic-to-jpg",
    iconColor: "info",
    type: "convert",
    buildStatus: "shipped",
    domain: "image",
    paywall: "always-free",
    keywords: [
      "heic to jpg", "heic to jpeg", "iphone photo to jpg", "convert heic",
      "heic converter", "heif to jpg", "iphone foto jpg",
      "heic ko jpg banao", "iphone photo convert",
      "एचईआईसी", "आईफोन फोटो",
      "portal heic", "sarkari form iphone photo",
    ],
    inputAccept: ["image/heic", "image/heif"],
    needsWorker: false,
    needsWasm: ["heic"],
    decodedPixelCap: 16_000_000,
    popularityScore: 0.7,
    nextSteps: ["image-compress", "photo-resize", "jpg-to-pdf"],
  },
  {
    slug: "photo-grayscale",
    href: "/photo-grayscale",
    name: "Photo Grayscale Converter",
    tagline: "Convert a colour photo to clean black & white",
    description:
      "Some sarkari portals and print shops want greyscale. One click, on-device, no quality loss.",
    status: "live",
    category: "forms",
    iconKind: "photo-grayscale",
    iconColor: "neutral",
    type: "enhance",
    buildStatus: "shipped",
    domain: "image",
    paywall: "always-free",
    keywords: [
      "grayscale photo", "greyscale photo", "black and white photo", "b&w photo",
      "photo bw", "photo greyscale", "photo black white karo",
      "ब्लैक एंड व्हाइट फोटो", "ग्रेस्केल",
      "convert to grayscale", "remove colour",
    ],
    inputAccept: IMAGE_ACCEPT,
    needsWorker: false,
    decodedPixelCap: 16_000_000,
    nextSteps: ["image-compress", "jpg-to-pdf", "print-sheet"],
  },
  {
    slug: "aadhaar-collage",
    href: "/aadhaar-collage",
    name: "Aadhaar Front + Back Collage",
    tagline: "Combine both sides on a single A4 sheet",
    description:
      "Stack front and back of an Aadhaar card on one A4 page, ready for portals that ask for both sides as a single upload.",
    status: "live",
    category: "forms",
    iconKind: "aadhaar-collage",
    iconColor: "warning",
    type: "compose",
    buildStatus: "shipped",
    domain: "sarkari",
    paywall: "always-free",
    keywords: [
      "aadhaar collage", "aadhaar front back", "aadhaar one page", "aadhaar combine",
      "id card collage", "front back collage",
      "आधार फ्रंट बैक", "आधार एक पेज",
      "aadhar collage", "adhar dono side",
    ],
    inputAccept: ["image/jpeg", "image/png"],
    needsWorker: false,
    nextSteps: ["pdf-compress", "image-compress"],
  },
  {
    slug: "bg-remove",
    href: "/bg-remove",
    name: "Background Remover",
    tagline: "Remove or replace image background — AI, in-browser",
    description:
      "Remove the background from any photo instantly. Keep it transparent (PNG) or replace with white — perfect for exam photos, ID cards, and e-commerce. Runs entirely in your browser.",
    status: "live",
    category: "forms",
    iconKind: "bg-remove",
    iconColor: "success",
    type: "enhance",
    buildStatus: "shipped",
    domain: "image",
    paywall: "always-free",
    keywords: [
      "background remover", "remove background", "bg remove", "background remove",
      "photo background hatao", "background cut karo", "background change",
      "transparent background", "white background", "bg remove online",
      "बैकग्राउंड हटाओ", "बैकग्राउंड रिमूवर",
      "exam photo bg", "passport photo white background", "id photo background",
      "cut out image", "remove bg", "ai background remover",
    ],
    inputAccept: IMAGE_ACCEPT,
    needsWorker: false,
    decodedPixelCap: 16_000_000,
    popularityScore: 0.9,
    nextSteps: ["image-compress", "photo-resize", "jpg-to-pdf"],
  },
  {
    slug: "batch-compress",
    href: "/batch-compress",
    name: "Batch Image Compressor",
    tagline: "Compress multiple images to one KB target in one go",
    description:
      "Upload up to 20 images at once. Pick a preset (20 KB, 50 KB, 100 KB, 200 KB) and compress all to the same target. Download each file individually.",
    status: "live",
    category: "forms",
    iconKind: "batch-compress",
    iconColor: "info",
    type: "compress-to-target",
    buildStatus: "shipped",
    domain: "image",
    paywall: "always-free",
    keywords: [
      "batch compress", "compress multiple images", "bulk compress", "compress all photos",
      "multiple image compress", "batch photo resize", "bulk image compressor",
      "sab photo compress karo", "multiple photo ek saath",
      "बैच कम्प्रेस", "सभी फोटो कम्प्रेस",
      "compress 10 photos", "compress all exam photos",
    ],
    inputAccept: IMAGE_ACCEPT,
    needsWorker: false,
    decodedPixelCap: 16_000_000,
    popularityScore: 0.75,
  },
  {
    slug: "quick-send",
    href: "/quick-send",
    name: "Quick Send",
    tagline: "Send files to a print shop - scan a QR, no app, no number",
    description:
      "Browser-to-browser file transfer. Print-shop opens Quick Send, customer scans the QR with their phone and sends files directly. P2P - files never stored on a server.",
    status: "live",
    category: "sharing",
    iconKind: "quick-send",
    iconColor: "info",
    type: "transfer",
    buildStatus: "shipped",
    domain: "utility",
    paywall: "always-free",
    keywords: [
      "quick send", "send files", "share files", "transfer files", "p2p file transfer",
      "file bhejna", "file share karo", "qr se file", "print shop ko bhejo",
      "फाइल भेजो", "फाइल शेयर",
      "wifi file transfer", "phone to laptop", "send to print shop",
    ],
    inputAccept: ["*/*"],
    needsWorker: false,
  },
  {
    slug: "aadhaar-mask",
    href: "/aadhaar-mask",
    name: "Aadhaar Masking",
    tagline: "Redact the Aadhaar number before sharing",
    description:
      "Draw black bars over the 12-digit number on your Aadhaar card image. UIDAI-recommended masking of the first 8 digits — runs entirely in your browser, nothing uploaded.",
    status: "live",
    category: "forms",
    iconKind: "aadhaar-mask",
    iconColor: "warning",
    type: "enhance",
    buildStatus: "shipped",
    domain: "image",
    paywall: "always-free",
    keywords: [
      "aadhaar masking", "aadhaar mask", "hide aadhaar number", "redact aadhaar",
      "aadhaar number chhupao", "aadhaar number hatao", "mask aadhaar",
      "आधार मास्किंग", "आधार नंबर छुपाओ",
      "aadhaar blur", "aadhaar redact", "dpdp aadhaar", "kyc masking",
      "black out aadhaar", "censor aadhaar number",
    ],
    inputAccept: ["image/jpeg", "image/png", "image/webp"],
    needsWorker: false,
    popularityScore: 0.8,
    nextSteps: ["aadhaar-collage", "jpg-to-pdf", "image-compress"],
  },
  {
    slug: "pdf-password",
    href: "/pdf-password",
    name: "PDF Password Protect",
    tagline: "Encrypt a PDF before you email it",
    description:
      "Add a password to any PDF before sending it to a client or colleague. AES-128 encryption runs in your browser — the file never touches a server.",
    status: "live",
    category: "utility",
    iconKind: "pdf-password",
    iconColor: "error",
    type: "enhance",
    buildStatus: "shipped",
    domain: "pdf",
    paywall: "always-free",
    keywords: [
      "pdf password", "pdf encrypt", "password protect pdf", "lock pdf",
      "pdf ko lock karo", "pdf password lagao", "secure pdf",
      "पीडीएफ पासवर्ड", "पीडीएफ एन्क्रिप्ट",
      "pdf protect", "encrypt pdf online", "add password to pdf",
      "pdf secure karo", "client ke liye pdf lock",
    ],
    inputAccept: ["application/pdf"],
    needsWorker: false,
    popularityScore: 0.7,
    nextSteps: ["pdf-compress", "pdf-merge-split"],
  },
  {
    slug: "pdf-page-manager",
    href: "/pdf-page-manager",
    name: "PDF Page Manager",
    tagline: "Reorder or delete pages from any PDF",
    description: "Drag pages into the right order or delete unwanted ones. Everything runs in your browser — the file never leaves your device.",
    status: "live",
    category: "utility",
    iconKind: "pdf-page-manager",
    iconColor: "info",
    type: "enhance",
    buildStatus: "shipped",
    domain: "pdf",
    paywall: "always-free",
    keywords: [
      "reorder pdf pages", "delete pdf pages", "remove page from pdf",
      "pdf page order", "rearrange pdf", "pdf organize pages",
      "pdf page delete online", "pdf pages reorder free",
    ],
    inputAccept: ["application/pdf"],
    needsWorker: true,
    popularityScore: 0.65,
    nextSteps: ["pdf-compress", "pdf-merge-split"],
  },
  {
    slug: "pdf-page-numbers",
    href: "/pdf-page-numbers",
    name: "PDF Page Numbers",
    tagline: "Stamp page numbers on any PDF",
    description: "Add page numbers to your PDF — bottom center, top right, or any corner. Runs entirely in your browser.",
    status: "live",
    category: "utility",
    iconKind: "pdf-page-numbers",
    iconColor: "accent",
    type: "enhance",
    buildStatus: "shipped",
    domain: "pdf",
    paywall: "always-free",
    keywords: [
      "add page numbers to pdf", "pdf page numbering", "number pdf pages",
      "pdf page number stamp", "pdf folio", "pdf page number online free",
    ],
    inputAccept: ["application/pdf"],
    needsWorker: false,
    popularityScore: 0.6,
    nextSteps: ["pdf-watermark", "pdf-compress"],
  },
  {
    slug: "pdf-watermark",
    href: "/pdf-watermark",
    name: "PDF Watermark",
    tagline: "Add a text watermark to every page",
    description: "Stamp CONFIDENTIAL, DRAFT, your name, or any text across every page of your PDF. Opacity and position are configurable. Runs in your browser.",
    status: "live",
    category: "utility",
    iconKind: "pdf-watermark",
    iconColor: "warning",
    type: "enhance",
    buildStatus: "shipped",
    domain: "pdf",
    paywall: "always-free",
    keywords: [
      "add watermark to pdf", "pdf watermark online", "pdf watermark free",
      "stamp pdf", "confidential watermark pdf", "draft watermark pdf",
      "pdf watermark text", "watermark pdf india",
    ],
    inputAccept: ["application/pdf"],
    needsWorker: false,
    popularityScore: 0.6,
    nextSteps: ["pdf-password", "pdf-compress"],
  },
  {
    slug: "pdf-redact",
    href: "/pdf-redact",
    name: "PDF Redact",
    tagline: "Permanently black out sensitive text in PDFs",
    description: "Draw black boxes over any area — Aadhaar number, signature, address — and burn them in permanently. No server, no uploads.",
    status: "live",
    category: "utility",
    iconKind: "pdf-redact",
    iconColor: "error",
    type: "enhance",
    buildStatus: "shipped",
    domain: "pdf",
    paywall: "always-free",
    keywords: [
      "pdf redact", "black out pdf text", "redact pdf online",
      "remove sensitive info pdf", "aadhaar redact pdf", "pdf censor",
      "pdf redaction tool free", "hide text in pdf",
    ],
    inputAccept: ["application/pdf"],
    needsWorker: true,
    popularityScore: 0.7,
    nextSteps: ["aadhaar-mask", "pdf-password"],
  },
  {
    slug: "pdf-sign",
    href: "/pdf-sign",
    name: "Sign PDF",
    tagline: "Add your signature to any PDF",
    description: "Draw, type, or upload your signature and place it on any PDF page. Runs entirely in your browser — nothing uploaded.",
    status: "live",
    category: "utility",
    iconKind: "pdf-sign",
    iconColor: "accent",
    type: "enhance",
    buildStatus: "shipped",
    domain: "pdf",
    paywall: "always-free",
    keywords: [
      "sign pdf online", "pdf signature", "add signature to pdf",
      "pdf sign free", "electronic signature pdf", "pdf par sign karo",
      "digital signature pdf india", "sign pdf no upload",
    ],
    inputAccept: ["application/pdf"],
    needsWorker: true,
    popularityScore: 0.85,
    nextSteps: ["pdf-password", "pdf-compress"],
  },
  {
    slug: "pdf-unlock",
    href: "/pdf-unlock",
    name: "Unlock PDF",
    tagline: "Remove password from a PDF you own",
    description: "Enter the password for your locked PDF and get an unlocked copy. All processing happens in your browser.",
    status: "live",
    category: "utility",
    iconKind: "pdf-unlock",
    iconColor: "warning",
    type: "enhance",
    buildStatus: "shipped",
    domain: "pdf",
    paywall: "always-free",
    keywords: [
      "unlock pdf", "remove pdf password", "pdf password remove",
      "pdf unlock online free", "pdf ka lock hatao", "unlock pdf india",
      "pdf password remover", "decrypt pdf",
    ],
    inputAccept: ["application/pdf"],
    needsWorker: false,
    popularityScore: 0.75,
    nextSteps: ["pdf-compress", "pdf-merge-split"],
  },
  {
    slug: "pdf-crop",
    href: "/pdf-crop",
    name: "Crop PDF",
    tagline: "Trim margins from PDF pages",
    description: "Remove unwanted white margins from your PDF. Set top, bottom, left, right trim values in mm. Runs in your browser.",
    status: "live",
    category: "utility",
    iconKind: "pdf-crop",
    iconColor: "success",
    type: "enhance",
    buildStatus: "shipped",
    domain: "pdf",
    paywall: "always-free",
    keywords: [
      "crop pdf", "trim pdf margins", "pdf margin remove",
      "pdf crop online free", "pdf borders hatao", "trim pdf pages",
      "pdf page crop", "reduce pdf margins",
    ],
    inputAccept: ["application/pdf"],
    needsWorker: false,
    popularityScore: 0.55,
    nextSteps: ["pdf-compress", "pdf-page-manager"],
  },
  {
    slug: "pdf-flatten",
    href: "/pdf-flatten",
    name: "Flatten PDF",
    tagline: "Lock form fields before sharing",
    description: "Flatten interactive PDF form fields so they can't be edited. Essential before emailing filled government forms.",
    status: "live",
    category: "utility",
    iconKind: "pdf-flatten",
    iconColor: "neutral",
    type: "enhance",
    buildStatus: "shipped",
    domain: "pdf",
    paywall: "always-free",
    keywords: [
      "flatten pdf", "lock pdf form fields", "pdf flatten online",
      "pdf form lock", "pdf non-editable", "flatten pdf form free",
      "pdf fields remove", "pdf flatten karo",
    ],
    inputAccept: ["application/pdf"],
    needsWorker: false,
    popularityScore: 0.5,
    nextSteps: ["pdf-password", "pdf-compress"],
  },
  {
    slug: "pdf-ocr",
    href: "/pdf-ocr",
    name: "PDF OCR",
    tagline: "Extract text from scanned PDFs",
    description: "Run OCR on scanned or image-based PDFs and extract the text. Supports English and Hindi. Runs in your browser using Tesseract.",
    status: "live",
    category: "utility",
    iconKind: "pdf-ocr",
    iconColor: "info",
    type: "extract",
    buildStatus: "shipped",
    domain: "pdf",
    paywall: "always-free",
    keywords: [
      "pdf ocr", "scanned pdf to text", "extract text from pdf",
      "pdf text extract online", "ocr pdf hindi", "pdf ocr free india",
      "image pdf to text", "pdf ocr tesseract",
    ],
    inputAccept: ["application/pdf"],
    needsWorker: true,
    popularityScore: 0.7,
    nextSteps: ["image-to-text", "pdf-compress"],
  },
  {
    slug: "scan-to-pdf",
    href: "/scan-to-pdf",
    name: "Scan to PDF",
    tagline: "Turn camera photos into a PDF",
    description: "Capture pages with your camera or upload photos and combine them into a single PDF. No app install needed — runs fully in your browser.",
    status: "live",
    category: "utility",
    iconKind: "scan-to-pdf",
    iconColor: "info",
    type: "compose",
    buildStatus: "shipped",
    domain: "pdf",
    paywall: "always-free",
    keywords: [
      "scan to pdf", "camera scan pdf", "photo to pdf", "scan document phone",
      "mobile scanner pdf", "document scanner online", "scan pdf free india",
    ],
    inputAccept: ["image/png", "image/jpeg", "image/webp"],
    needsWorker: false,
    popularityScore: 0.75,
    nextSteps: ["pdf-compress", "pdf-ocr"],
  },
  {
    slug: "pdf-form-filler",
    href: "/pdf-form-filler",
    name: "PDF Form Filler",
    tagline: "Fill PDF forms in your browser",
    description: "Upload a fillable PDF, fill in all form fields, and download the completed PDF. Works on AcroForms — no Adobe Acrobat needed.",
    status: "live",
    category: "utility",
    iconKind: "pdf-form-filler",
    iconColor: "info",
    type: "compose",
    buildStatus: "shipped",
    domain: "pdf",
    paywall: "always-free",
    keywords: [
      "pdf form filler", "fill pdf form online", "pdf form fill free",
      "acroform filler", "fill pdf without adobe", "pdf form india",
    ],
    inputAccept: ["application/pdf"],
    needsWorker: false,
    popularityScore: 0.72,
    nextSteps: ["pdf-flatten", "pdf-compress"],
  },
  {
    slug: "image-watermark",
    href: "/image-watermark",
    name: "Image Watermark",
    tagline: "Add text watermark to images",
    description: "Add a custom text watermark to any image — JPG, PNG, or WebP. Control position, opacity, size, and color. Runs in your browser, no upload.",
    status: "live",
    category: "utility",
    iconKind: "image-watermark",
    iconColor: "accent",
    type: "enhance",
    buildStatus: "shipped",
    domain: "image",
    paywall: "always-free",
    keywords: [
      "image watermark", "add watermark photo", "watermark image online free",
      "photo watermark tool india", "text watermark image", "watermark png jpg",
    ],
    inputAccept: ["image/png", "image/jpeg", "image/webp"],
    needsWorker: false,
    popularityScore: 0.68,
    nextSteps: ["image-resize", "image-compress"],
  },
  {
    slug: "image-resize",
    href: "/image-resize",
    name: "Image Resize",
    tagline: "Resize images by pixel or percent",
    description: "Resize any image to exact pixel dimensions or by percentage. Supports JPG, PNG, WebP with aspect ratio lock. No server upload — all browser.",
    status: "live",
    category: "utility",
    iconKind: "image-resize",
    iconColor: "accent",
    type: "resize-to-spec",
    buildStatus: "shipped",
    domain: "image",
    paywall: "always-free",
    keywords: [
      "image resize online", "resize photo free", "resize image pixels",
      "compress resize image india", "photo resize tool", "png jpg resize",
    ],
    inputAccept: ["image/png", "image/jpeg", "image/webp"],
    needsWorker: false,
    popularityScore: 0.8,
    nextSteps: ["image-compress", "image-watermark"],
  },
  {
    slug: "text-to-pdf",
    href: "/text-to-pdf",
    name: "Text to PDF",
    tagline: "Convert plain text to a PDF",
    description: "Paste any plain text and convert it to a downloadable PDF with clean formatting. Auto-paginates long text. Runs entirely in your browser.",
    status: "live",
    category: "utility",
    iconKind: "text-to-pdf",
    iconColor: "info",
    type: "convert",
    buildStatus: "shipped",
    domain: "pdf",
    paywall: "always-free",
    keywords: [
      "text to pdf", "convert text to pdf", "plain text pdf", "txt to pdf free",
      "notepad to pdf", "text pdf converter india",
    ],
    inputAccept: [],
    needsWorker: false,
    popularityScore: 0.65,
    nextSteps: ["pdf-compress", "pdf-merge-split"],
  },
  {
    slug: "pdf-repair",
    href: "/pdf-repair",
    name: "PDF Repair",
    tagline: "Fix corrupted or broken PDFs",
    description: "Try to recover and repair a damaged, corrupted, or partially broken PDF. Reloads the file with fault-tolerant parsing and re-saves a clean copy.",
    status: "live",
    category: "utility",
    iconKind: "pdf-repair",
    iconColor: "warning",
    type: "enhance",
    buildStatus: "shipped",
    domain: "pdf",
    paywall: "always-free",
    keywords: [
      "pdf repair", "fix corrupted pdf", "repair pdf free", "broken pdf fix",
      "recover pdf", "pdf repair tool india",
    ],
    inputAccept: ["application/pdf"],
    needsWorker: false,
    popularityScore: 0.6,
    nextSteps: ["pdf-compress", "pdf-merge-split"],
  },
  {
    slug: "gst-invoice",
    href: "/gst-invoice",
    name: "GST Invoice Generator",
    tagline: "Create GST invoices in seconds",
    description: "Generate GST-compliant tax invoices in your browser. Fill seller and buyer details, add line items with HSN codes, and print or save as PDF. Free, no signup.",
    status: "live",
    category: "forms",
    iconKind: "gst-invoice",
    iconColor: "success",
    type: "generate",
    buildStatus: "shipped",
    domain: "sarkari",
    paywall: "always-free",
    keywords: [
      "gst invoice generator", "gst bill format", "gst invoice online free",
      "tax invoice india", "gst billing software free", "gst invoice pdf",
    ],
    inputAccept: [],
    needsWorker: false,
    popularityScore: 0.85,
    nextSteps: ["salary-slip", "affidavit"],
  },
  {
    slug: "salary-slip",
    href: "/salary-slip",
    name: "Salary Slip Generator",
    tagline: "Generate professional salary slips",
    description: "Create professional salary slips / pay slips in your browser. Add earnings, deductions, PF, TDS, and print or save as PDF. No signup required.",
    status: "live",
    category: "forms",
    iconKind: "salary-slip",
    iconColor: "success",
    type: "generate",
    buildStatus: "shipped",
    domain: "sarkari",
    paywall: "always-free",
    keywords: [
      "salary slip generator", "pay slip maker india", "salary slip pdf free",
      "payslip format india", "salary certificate maker", "monthly salary slip",
    ],
    inputAccept: [],
    needsWorker: false,
    popularityScore: 0.82,
    nextSteps: ["gst-invoice", "affidavit"],
  },
  {
    slug: "affidavit",
    href: "/affidavit",
    name: "Affidavit Generator",
    tagline: "Draft affidavits on stamp paper format",
    description: "Generate affidavits in Indian stamp paper format for common use cases — name change, address proof, income, marital status, and more. Print-ready.",
    status: "live",
    category: "forms",
    iconKind: "affidavit",
    iconColor: "warning",
    type: "generate",
    buildStatus: "shipped",
    domain: "sarkari",
    paywall: "always-free",
    keywords: [
      "affidavit generator india", "affidavit format india", "affidavit pdf free",
      "stamp paper affidavit", "name change affidavit", "affidavit maker online",
    ],
    inputAccept: [],
    needsWorker: false,
    popularityScore: 0.78,
    nextSteps: ["rent-agreement", "gst-invoice"],
  },
  {
    slug: "rent-agreement",
    href: "/rent-agreement",
    name: "Rent Agreement",
    tagline: "Draft a Leave & Licence agreement",
    description: "Generate a standard Leave and Licence rent agreement for Indian residential tenancies. Fill landlord/tenant details and get a print-ready document.",
    status: "live",
    category: "forms",
    iconKind: "rent-agreement",
    iconColor: "warning",
    type: "generate",
    buildStatus: "shipped",
    domain: "sarkari",
    paywall: "always-free",
    keywords: [
      "rent agreement india", "leave and licence agreement", "rent agreement pdf",
      "rental agreement format india", "house rent agreement", "lease agreement india free",
    ],
    inputAccept: [],
    needsWorker: false,
    popularityScore: 0.8,
    nextSteps: ["affidavit", "gst-invoice"],
  },
  {
    slug: "zip-tool",
    href: "/zip-tool",
    name: "ZIP Tool",
    tagline: "Create and extract ZIP files",
    description: "Create ZIP archives from multiple files or extract contents of any ZIP file — all in your browser. No server upload, no installation needed.",
    status: "live",
    category: "utility",
    iconKind: "zip-tool",
    iconColor: "neutral",
    type: "convert",
    buildStatus: "shipped",
    domain: "utility",
    paywall: "always-free",
    keywords: [
      "zip file online", "create zip free", "extract zip online", "zip extractor",
      "zip maker browser", "zip tool india free",
    ],
    inputAccept: [],
    needsWorker: false,
    popularityScore: 0.7,
    nextSteps: ["pdf-merge-split", "image-compress"],
  },
  // ─── New tools batch 3 ───────────────────────────────────────────────────
  {
    slug: "pdf-to-images",
    href: "/pdf-to-images",
    name: "PDF to Images",
    tagline: "Export every PDF page as PNG",
    description: "Convert each page of a PDF to a high-quality PNG image. Download all pages as a ZIP. Runs entirely in your browser using PDF.js.",
    status: "live", category: "utility", iconKind: "pdf-to-images", iconColor: "info",
    type: "extract", buildStatus: "shipped", domain: "pdf", paywall: "always-free",
    keywords: ["pdf to image", "pdf to png", "pdf page to image", "convert pdf pages png", "pdf images export"],
    inputAccept: ["application/pdf"], needsWorker: false, popularityScore: 0.75,
    nextSteps: ["image-compress", "pdf-compress"],
  },
  {
    slug: "pdf-metadata",
    href: "/pdf-metadata",
    name: "PDF Metadata Editor",
    tagline: "Edit PDF title, author, subject",
    description: "View and edit the metadata of any PDF — title, author, subject, keywords, and creator. Download the updated PDF. Runs in your browser.",
    status: "live", category: "utility", iconKind: "pdf-metadata", iconColor: "neutral",
    type: "enhance", buildStatus: "shipped", domain: "pdf", paywall: "always-free",
    keywords: ["pdf metadata editor", "edit pdf properties", "pdf title author", "pdf info editor", "change pdf metadata"],
    inputAccept: ["application/pdf"], needsWorker: false, popularityScore: 0.55,
    nextSteps: ["pdf-compress", "pdf-merge-split"],
  },
  {
    slug: "image-to-base64",
    href: "/image-to-base64",
    name: "Image to Base64",
    tagline: "Encode or decode images as Base64",
    description: "Convert any image to a Base64 string for use in HTML, CSS, or JSON. Or decode a Base64 string back to an image. Runs in your browser.",
    status: "live", category: "utility", iconKind: "image-to-base64", iconColor: "neutral",
    type: "convert", buildStatus: "shipped", domain: "image", paywall: "always-free",
    keywords: ["image to base64", "base64 encoder", "image base64 converter", "encode image base64", "base64 decode image"],
    inputAccept: ["image/png", "image/jpeg", "image/webp", "image/gif", "image/svg+xml"], needsWorker: false, popularityScore: 0.65,
    nextSteps: ["image-compress", "svg-to-png"],
  },
  {
    slug: "image-color-picker",
    href: "/image-color-picker",
    name: "Image Color Picker",
    tagline: "Pick any color from an image",
    description: "Upload an image and click any pixel to get its HEX, RGB, and HSL color values. Also extracts a 10-color dominant palette from the image.",
    status: "live", category: "utility", iconKind: "image-color-picker", iconColor: "accent",
    type: "extract", buildStatus: "shipped", domain: "image", paywall: "always-free",
    keywords: ["image color picker", "pick color from image", "color extractor", "eyedropper tool online", "dominant color palette"],
    inputAccept: ["image/png", "image/jpeg", "image/webp"], needsWorker: false, popularityScore: 0.7,
    nextSteps: ["color-convert", "palette-builder"],
  },
  {
    slug: "experience-letter",
    href: "/experience-letter",
    name: "Experience Letter Generator",
    tagline: "Generate work experience certificates",
    description: "Create a professional experience letter / work experience certificate. Fill company and employee details and print or save as PDF.",
    status: "live", category: "forms", iconKind: "experience-letter", iconColor: "success",
    type: "generate", buildStatus: "shipped", domain: "sarkari", paywall: "always-free",
    keywords: ["experience letter", "work experience certificate", "experience certificate format", "experience letter india", "employment certificate"],
    inputAccept: [], needsWorker: false, popularityScore: 0.8,
    nextSteps: ["noc-generator", "salary-slip"],
  },
  {
    slug: "noc-generator",
    href: "/noc-generator",
    name: "NOC Generator",
    tagline: "Draft No Objection Certificates",
    description: "Generate a No Objection Certificate for travel, job change, vehicle transfer, or property. Fill details and print or save as PDF.",
    status: "live", category: "forms", iconKind: "noc-generator", iconColor: "success",
    type: "generate", buildStatus: "shipped", domain: "sarkari", paywall: "always-free",
    keywords: ["noc generator", "no objection certificate", "noc format india", "noc letter", "noc pdf free"],
    inputAccept: [], needsWorker: false, popularityScore: 0.78,
    nextSteps: ["affidavit", "experience-letter"],
  },
  {
    slug: "bonafide-certificate",
    href: "/bonafide-certificate",
    name: "Bonafide Certificate",
    tagline: "Generate bonafide certificates",
    description: "Create a bonafide certificate from schools, colleges, or employers. Fill institution and student/employee details and print or save as PDF.",
    status: "live", category: "forms", iconKind: "bonafide-certificate", iconColor: "success",
    type: "generate", buildStatus: "shipped", domain: "sarkari", paywall: "always-free",
    keywords: ["bonafide certificate", "bonafide certificate format india", "bonafide letter", "student bonafide", "bonafide certificate free"],
    inputAccept: [], needsWorker: false, popularityScore: 0.76,
    nextSteps: ["experience-letter", "affidavit"],
  },
  {
    slug: "cheque-print",
    href: "/cheque-print",
    name: "Cheque Print Tool",
    tagline: "Print cheques neatly every time",
    description: "Fill cheque details and print a cheque-sized layout to place over a blank cheque. Supports all major Indian banks. Amount in words auto-computed.",
    status: "live", category: "forms", iconKind: "cheque-print", iconColor: "warning",
    type: "generate", buildStatus: "shipped", domain: "sarkari", paywall: "always-free",
    keywords: ["cheque print", "cheque printing tool", "print cheque india", "cheque format", "cheque amount in words"],
    inputAccept: [], needsWorker: false, popularityScore: 0.72,
    nextSteps: ["gst-invoice", "salary-slip"],
  },
  {
    slug: "emi-calculator",
    href: "/emi-calculator",
    name: "EMI Calculator",
    tagline: "Calculate loan EMI with amortization",
    description: "Calculate monthly EMI for home, car, or personal loans. See total interest, total payment, and a month-by-month amortization table. Indian number formatting.",
    status: "live", category: "utility", iconKind: "emi-calculator", iconColor: "info",
    type: "generate", buildStatus: "shipped", domain: "utility", paywall: "always-free",
    keywords: ["emi calculator", "loan emi calculator india", "home loan emi", "car loan emi", "personal loan emi", "emi calculation formula"],
    inputAccept: [], needsWorker: false, popularityScore: 0.9,
    nextSteps: ["gst-invoice", "salary-slip"],
  },
  {
    slug: "unit-converter",
    href: "/unit-converter",
    name: "Unit Converter",
    tagline: "Convert units including Indian lakh/crore",
    description: "Convert between length, weight, area, volume, and temperature units. Includes Indian units like bigha, gunta, lakh, and crore.",
    status: "live", category: "utility", iconKind: "unit-converter", iconColor: "neutral",
    type: "convert", buildStatus: "shipped", domain: "utility", paywall: "always-free",
    keywords: ["unit converter", "unit converter india", "bigha to meter", "lakh crore converter", "length weight converter online"],
    inputAccept: [], needsWorker: false, popularityScore: 0.82,
    nextSteps: ["word-counter", "emi-calculator"],
  },
  {
    slug: "word-counter",
    href: "/word-counter",
    name: "Word Counter",
    tagline: "Count words, chars, reading time",
    description: "Count words, characters, sentences, paragraphs, reading time, and speaking time. Includes Flesch readability score and keyword density analysis.",
    status: "live", category: "utility", iconKind: "word-counter", iconColor: "neutral",
    type: "extract", buildStatus: "shipped", domain: "utility", paywall: "always-free",
    keywords: ["word counter", "character counter", "word count online", "reading time calculator", "text statistics tool"],
    inputAccept: [], needsWorker: false, popularityScore: 0.85,
    nextSteps: ["text-to-pdf", "unit-converter"],
  },
  {
    slug: "barcode-generator",
    href: "/barcode-generator",
    name: "Barcode Generator",
    tagline: "Generate Code128, EAN, QR barcodes",
    description: "Generate barcodes in Code128, EAN-13, EAN-8, UPC-A, PDF417, DataMatrix, and QR formats. Download as PNG or SVG. Runs in your browser.",
    status: "live", category: "utility", iconKind: "barcode-generator", iconColor: "neutral",
    type: "generate", buildStatus: "shipped", domain: "utility", paywall: "always-free",
    keywords: ["barcode generator", "barcode maker online", "qr barcode generator", "ean13 barcode", "code128 barcode free"],
    inputAccept: [], needsWorker: false, popularityScore: 0.75,
    nextSteps: ["qr-generate", "placeholder-img"],
  },
  {
    slug: "svg-to-png",
    href: "/svg-to-png",
    name: "SVG to PNG",
    tagline: "Convert SVG to PNG at any resolution",
    description: "Convert SVG files to PNG at any resolution. Upload an SVG file or paste SVG code, set dimensions and scale, and download the PNG.",
    status: "live", category: "utility", iconKind: "svg-to-png", iconColor: "accent",
    type: "convert", buildStatus: "shipped", domain: "image", paywall: "always-free",
    keywords: ["svg to png", "convert svg png", "svg export png", "svg image converter", "svg to image online"],
    inputAccept: ["image/svg+xml"], needsWorker: false, popularityScore: 0.72,
    nextSteps: ["image-compress", "favicon-maker"],
  },
  {
    slug: "svg-viewer",
    href: "/svg-viewer",
    name: "SVG Viewer & Editor",
    tagline: "View and edit SVG code side-by-side",
    description: "View and edit SVG code with a live preview panel. Upload an SVG or paste code, see it render instantly, and download the result.",
    status: "live", category: "utility", iconKind: "svg-viewer", iconColor: "accent",
    type: "enhance", buildStatus: "shipped", domain: "image", paywall: "always-free",
    keywords: ["svg viewer", "svg editor online", "svg preview", "svg code editor", "svg live preview"],
    inputAccept: ["image/svg+xml"], needsWorker: false, popularityScore: 0.65,
    nextSteps: ["svg-to-png", "image-compress"],
  },
  {
    slug: "contrast-checker",
    href: "/contrast-checker",
    name: "Color Contrast Checker",
    tagline: "Check WCAG AA/AAA contrast ratios",
    description: "Check WCAG color contrast ratios for accessibility. Enter foreground and background colors to see the contrast ratio and AA/AAA pass/fail results.",
    status: "live", category: "utility", iconKind: "contrast-checker", iconColor: "warning",
    type: "extract", buildStatus: "shipped", domain: "utility", paywall: "always-free",
    keywords: ["contrast checker", "wcag contrast ratio", "color contrast accessibility", "aa contrast check", "color accessibility tool"],
    inputAccept: [], needsWorker: false, popularityScore: 0.7,
    nextSteps: ["color-convert", "palette-builder"],
  },
  {
    slug: "color-convert",
    href: "/color-convert",
    name: "Color Format Converter",
    tagline: "Convert HEX, RGB, HSL, CMYK colors",
    description: "Convert between HEX, RGB, HSL, HSV, CMYK, and oklch color formats instantly. Click any format to copy. No signup needed.",
    status: "live", category: "utility", iconKind: "color-convert", iconColor: "accent",
    type: "convert", buildStatus: "shipped", domain: "utility", paywall: "always-free",
    keywords: ["color converter", "hex to rgb", "rgb to hsl", "color format converter", "hex rgb hsl converter online"],
    inputAccept: [], needsWorker: false, popularityScore: 0.75,
    nextSteps: ["contrast-checker", "palette-builder"],
  },
  {
    slug: "color-palette",
    href: "/color-palette",
    name: "Color Palette Extractor",
    tagline: "Extract dominant colors from any image",
    description: "Upload any image and extract a 10-color dominant palette. Export as CSS variables, Tailwind config, or hex list.",
    status: "live", category: "utility", iconKind: "color-palette", iconColor: "accent",
    type: "extract", buildStatus: "shipped", domain: "image", paywall: "always-free",
    keywords: ["color palette extractor", "extract colors from image", "dominant color palette", "image palette generator", "color palette from photo"],
    inputAccept: ["image/png", "image/jpeg", "image/webp"], needsWorker: false, popularityScore: 0.72,
    nextSteps: ["palette-builder", "color-convert"],
  },
  {
    slug: "palette-builder",
    href: "/palette-builder",
    name: "Color Palette Builder",
    tagline: "Build and export custom color palettes",
    description: "Build a custom color palette from scratch. Add, name, and reorder colors, then export as CSS variables, Tailwind config, or Figma tokens JSON.",
    status: "live", category: "utility", iconKind: "palette-builder", iconColor: "accent",
    type: "generate", buildStatus: "shipped", domain: "utility", paywall: "always-free",
    keywords: ["color palette builder", "custom palette creator", "design color palette", "css color variables", "tailwind color palette"],
    inputAccept: [], needsWorker: false, popularityScore: 0.68,
    nextSteps: ["color-palette", "gradient-maker"],
  },
  {
    slug: "gradient-maker",
    href: "/gradient-maker",
    name: "CSS Gradient Generator",
    tagline: "Create linear, radial, conic gradients",
    description: "Create and preview CSS gradients — linear, radial, and conic. Add color stops, set angles, and copy the CSS code. Includes popular presets.",
    status: "live", category: "utility", iconKind: "gradient-maker", iconColor: "accent",
    type: "generate", buildStatus: "shipped", domain: "utility", paywall: "always-free",
    keywords: ["css gradient generator", "gradient maker", "linear gradient css", "radial gradient tool", "conic gradient generator"],
    inputAccept: [], needsWorker: false, popularityScore: 0.7,
    nextSteps: ["palette-builder", "shadow-maker"],
  },
  {
    slug: "shadow-maker",
    href: "/shadow-maker",
    name: "CSS Box Shadow Generator",
    tagline: "Design box shadows visually",
    description: "Visually design CSS box shadows with multiple layers. Adjust offset, blur, spread, color, and inset per layer. Copy the CSS output.",
    status: "live", category: "utility", iconKind: "shadow-maker", iconColor: "neutral",
    type: "generate", buildStatus: "shipped", domain: "utility", paywall: "always-free",
    keywords: ["css box shadow generator", "box shadow maker", "shadow generator css", "css shadow tool", "box shadow designer"],
    inputAccept: [], needsWorker: false, popularityScore: 0.68,
    nextSteps: ["border-radius-tool", "gradient-maker"],
  },
  {
    slug: "border-radius-tool",
    href: "/border-radius-tool",
    name: "Border Radius Generator",
    tagline: "Set border-radius per corner visually",
    description: "Visually set border-radius for each corner independently. Toggle units (px/% /rem), link all corners, and copy the CSS output.",
    status: "live", category: "utility", iconKind: "border-radius-tool", iconColor: "neutral",
    type: "generate", buildStatus: "shipped", domain: "utility", paywall: "always-free",
    keywords: ["border radius generator", "css border radius tool", "rounded corners css", "border radius designer", "css radius maker"],
    inputAccept: [], needsWorker: false, popularityScore: 0.62,
    nextSteps: ["shadow-maker", "gradient-maker"],
  },
  {
    slug: "favicon-maker",
    href: "/favicon-maker",
    name: "Favicon Generator",
    tagline: "Generate all favicon sizes + manifest",
    description: "Upload a PNG or SVG and generate all favicon sizes (16×16 to 512×512) plus a web manifest JSON. Download as a ZIP. Runs in your browser.",
    status: "live", category: "utility", iconKind: "favicon-maker", iconColor: "info",
    type: "generate", buildStatus: "shipped", domain: "image", paywall: "always-free",
    keywords: ["favicon generator", "favicon maker", "favicon png all sizes", "website favicon", "favicon ico generator free"],
    inputAccept: ["image/png", "image/svg+xml"], needsWorker: false, popularityScore: 0.8,
    nextSteps: ["svg-to-png", "social-image-resize"],
  },
  {
    slug: "social-image-resize",
    href: "/social-image-resize",
    name: "Social Media Image Resizer",
    tagline: "Resize images for all social platforms",
    description: "Resize any image to exact social media dimensions — OG, Twitter, LinkedIn, Instagram, Facebook, YouTube thumbnail. Download all at once as a ZIP.",
    status: "live", category: "utility", iconKind: "social-image-resize", iconColor: "info",
    type: "resize-to-spec", buildStatus: "shipped", domain: "image", paywall: "always-free",
    keywords: ["social media image resize", "og image size", "twitter card size", "instagram image resize", "social image resizer free"],
    inputAccept: ["image/png", "image/jpeg", "image/webp"], needsWorker: false, popularityScore: 0.78,
    nextSteps: ["favicon-maker", "image-compress"],
  },
  {
    slug: "placeholder-img",
    href: "/placeholder-img",
    name: "Placeholder Image Generator",
    tagline: "Generate custom placeholder images",
    description: "Generate placeholder images at any size with custom background color, text color, and label. Download PNG or copy the data URI.",
    status: "live", category: "utility", iconKind: "placeholder-img", iconColor: "neutral",
    type: "generate", buildStatus: "shipped", domain: "image", paywall: "always-free",
    keywords: ["placeholder image generator", "dummy image generator", "placeholder img", "placeholder png", "fake image generator"],
    inputAccept: [], needsWorker: false, popularityScore: 0.65,
    nextSteps: ["social-image-resize", "favicon-maker"],
  },
  {
    slug: "css-unit-converter",
    href: "/css-unit-converter",
    name: "CSS Unit Converter",
    tagline: "Convert px, rem, em, pt, vw, vh",
    description: "Convert between px, rem, em, pt, vw, and vh CSS units. Set your base font size and viewport for accurate results. Includes a quick-reference table.",
    status: "live", category: "utility", iconKind: "css-unit-converter", iconColor: "neutral",
    type: "convert", buildStatus: "shipped", domain: "utility", paywall: "always-free",
    keywords: ["css unit converter", "px to rem converter", "rem to px", "em to px", "css units converter online"],
    inputAccept: [], needsWorker: false, popularityScore: 0.72,
    nextSteps: ["contrast-checker", "shadow-maker"],
  },
  {
    slug: "business-card-maker",
    href: "/business-card-maker",
    name: "Business Card Maker",
    tagline: "Design and download business cards",
    description: "Design a simple business card with your name, title, company, and contact details. Choose a template, download as PDF or PNG. No signup.",
    status: "live", category: "utility", iconKind: "business-card-maker", iconColor: "accent",
    type: "generate", buildStatus: "shipped", domain: "utility", paywall: "always-free",
    keywords: ["business card maker", "visiting card maker", "business card generator india", "visiting card design free", "business card pdf download"],
    inputAccept: [], needsWorker: false, popularityScore: 0.75,
    nextSteps: ["placeholder-img", "favicon-maker"],
  },
];

export function getToolBySlug(slug: string): Tool | undefined {
  return tools.find((t) => t.slug === slug);
}
