"use client";

import { useRef, useState } from "react";
import { Download, Image as ImageIcon, Upload } from "lucide-react";
import { Button } from "@devalok/shilp-sutra/ui/button";
import { toast } from "@devalok/shilp-sutra/ui/toast";
import { fire } from "@/lib/analytics/events";

// ── Constants ─────────────────────────────────────────────────────────────────

const FAVICON_SIZES = [16, 32, 48, 64, 96, 128, 180, 192, 512] as const;

// ── Helpers ───────────────────────────────────────────────────────────────────

function renderToCanvas(
  img: HTMLImageElement,
  size: number,
): Promise<Blob | null> {
  return new Promise((resolve) => {
    const canvas = document.createElement("canvas");
    canvas.width = size;
    canvas.height = size;
    const ctx = canvas.getContext("2d");
    if (!ctx) return resolve(null);
    ctx.drawImage(img, 0, 0, size, size);
    canvas.toBlob((blob) => resolve(blob), "image/png");
  });
}

function buildManifest(appName: string, shortName: string, themeColor: string): string {
  return JSON.stringify(
    {
      name: appName || "My App",
      short_name: shortName || appName || "App",
      icons: [
        { src: "/icon-192.png", sizes: "192x192", type: "image/png" },
        { src: "/icon-512.png", sizes: "512x512", type: "image/png" },
      ],
      theme_color: themeColor,
      background_color: "#ffffff",
      display: "standalone",
    },
    null,
    2,
  );
}

// ── Component ─────────────────────────────────────────────────────────────────

export function FaviconMakerForm() {
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [sourceFile, setSourceFile] = useState<File | null>(null);
  const [previewUrl, setPreviewUrl] = useState<string | null>(null);
  const [appName, setAppName] = useState("My App");
  const [shortName, setShortName] = useState("App");
  const [themeColor, setThemeColor] = useState("#ffffff");
  const [busy, setBusy] = useState(false);

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    const accepted = file.type === "image/png" || file.type === "image/svg+xml";
    if (!accepted) {
      toast.error("Please upload a PNG or SVG file.");
      return;
    }
    setSourceFile(file);
    const url = URL.createObjectURL(file);
    setPreviewUrl(url);
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    const file = e.dataTransfer.files[0];
    if (!file) return;
    const accepted = file.type === "image/png" || file.type === "image/svg+xml";
    if (!accepted) {
      toast.error("Please drop a PNG or SVG file.");
      return;
    }
    setSourceFile(file);
    const url = URL.createObjectURL(file);
    setPreviewUrl(url);
  };

  const handleDownload = async () => {
    if (!sourceFile) {
      toast.error("Please upload an image first.");
      return;
    }
    fire("process_start", { tool_id: "favicon-maker" });
    setBusy(true);
    try {
      // Load the source image
      const imgUrl = URL.createObjectURL(sourceFile);
      const img = await new Promise<HTMLImageElement>((resolve, reject) => {
        const el = new Image();
        el.onload = () => resolve(el);
        el.onerror = reject;
        el.src = imgUrl;
      });

      // eslint-disable-next-line @typescript-eslint/ban-ts-comment
      // @ts-ignore — jszip installed at build time
      const JSZip = (await import("jszip")).default;
      const zip = new JSZip();

      // Generate each size
      for (const size of FAVICON_SIZES) {
        const blob = await renderToCanvas(img, size);
        if (!blob) {
          toast.error(`Failed to render ${size}×${size}.`);
          continue;
        }
        const name =
          size === 180
            ? "apple-touch-icon.png"
            : size === 192
              ? "icon-192.png"
              : size === 512
                ? "icon-512.png"
                : `favicon-${size}x${size}.png`;
        zip.file(name, blob);
      }

      URL.revokeObjectURL(imgUrl);

      // Add manifest
      const manifest = buildManifest(appName, shortName, themeColor);
      zip.file("site.webmanifest", manifest);

      // Also add a readme hint
      const readme = [
        "Favicon Set — generated by BharatTools Favicon Generator",
        "",
        "Files included:",
        "  favicon-16x16.png       — browser tab icon",
        "  favicon-32x32.png       — browser tab icon (HiDPI)",
        "  favicon-48x48.png",
        "  favicon-64x64.png",
        "  favicon-96x96.png",
        "  favicon-128x128.png",
        "  apple-touch-icon.png    — iOS home screen (180×180)",
        "  icon-192.png            — Android / PWA",
        "  icon-512.png            — Android / PWA splash",
        "  site.webmanifest        — Web App Manifest",
        "",
        "Add to your <head>:",
        '  <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">',
        '  <link rel="apple-touch-icon" href="/apple-touch-icon.png">',
        '  <link rel="manifest" href="/site.webmanifest">',
      ].join("\n");
      zip.file("README.txt", readme);

      const zipBlob = await zip.generateAsync({ type: "blob", compression: "DEFLATE" });
      const url = URL.createObjectURL(zipBlob);
      const a = document.createElement("a");
      a.href = url;
      a.download = "favicons.zip";
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);

      fire("download_click", { tool_id: "favicon-maker", output_type: "application/zip" });
      toast.success("Favicon ZIP downloaded!");
    } catch (err) {
      console.error(err);
      toast.error("Failed to generate favicons. Check browser console.");
    } finally {
      setBusy(false);
    }
  };

  return (
    <div className="space-y-8">
      {/* Upload zone */}
      <div
        onDrop={handleDrop}
        onDragOver={(e) => e.preventDefault()}
        onClick={() => fileInputRef.current?.click()}
        className="flex cursor-pointer flex-col items-center justify-center gap-3 rounded-xl border-2 border-dashed border-surface-border p-10 text-center transition hover:border-primary-500 hover:bg-surface-2"
        role="button"
        aria-label="Drop a PNG or SVG file or click to browse"
      >
        <Upload className="size-8 text-surface-fg-muted" aria-hidden />
        <p className="text-body-sm text-surface-fg-muted">
          Drop a <span className="font-medium">PNG</span> or <span className="font-medium">SVG</span> here, or{" "}
          <span className="font-medium text-primary-600">click to browse</span>
        </p>
        <input
          ref={fileInputRef}
          type="file"
          accept=".png,.svg,image/png,image/svg+xml"
          className="sr-only"
          onChange={handleFileChange}
          tabIndex={-1}
        />
      </div>

      {/* Preview + size grid */}
      {previewUrl && (
        <div className="flex flex-col gap-6 sm:flex-row sm:items-start">
          {/* Preview */}
          <div className="flex flex-col items-center gap-2">
            <p className="text-body-xs font-medium text-surface-fg-muted uppercase tracking-wide">Source</p>
            <div className="h-32 w-32 overflow-hidden rounded-xl border border-surface-border bg-surface-2 p-2">
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={previewUrl}
                alt="Source favicon image"
                className="h-full w-full object-contain"
              />
            </div>
          </div>

          {/* Size chips */}
          <div className="flex-1">
            <p className="mb-3 text-body-xs font-medium uppercase tracking-wide text-surface-fg-muted">
              Sizes that will be generated
            </p>
            <div className="flex flex-wrap gap-2">
              {FAVICON_SIZES.map((size) => (
                <span
                  key={size}
                  className="flex items-center gap-1.5 rounded-full border border-surface-border bg-surface-2 px-3 py-1 text-body-xs text-surface-fg"
                >
                  <ImageIcon className="size-3 text-surface-fg-muted" aria-hidden />
                  {size === 180
                    ? `apple-touch-icon (${size})`
                    : `${size}×${size}`}
                </span>
              ))}
              <span className="flex items-center gap-1.5 rounded-full border border-surface-border bg-surface-2 px-3 py-1 text-body-xs text-surface-fg">
                site.webmanifest
              </span>
            </div>
          </div>
        </div>
      )}

      {/* Manifest options */}
      <div className="rounded-xl border border-surface-border bg-surface-1 p-5 space-y-4">
        <p className="text-body-sm font-semibold text-surface-fg">Web Manifest Settings</p>
        <div className="grid gap-4 sm:grid-cols-3">
          <div className="space-y-1.5">
            <label htmlFor="app-name" className="block text-body-sm font-medium">
              App name
            </label>
            <input
              id="app-name"
              type="text"
              value={appName}
              onChange={(e) => setAppName(e.target.value)}
              placeholder="My App"
              className="w-full rounded-md border border-surface-border bg-surface-1 px-3 py-2 text-body-sm text-surface-fg placeholder:text-surface-fg-muted focus:outline-none focus:ring-2 focus:ring-primary-500"
            />
          </div>
          <div className="space-y-1.5">
            <label htmlFor="short-name" className="block text-body-sm font-medium">
              Short name
            </label>
            <input
              id="short-name"
              type="text"
              value={shortName}
              onChange={(e) => setShortName(e.target.value)}
              placeholder="App"
              className="w-full rounded-md border border-surface-border bg-surface-1 px-3 py-2 text-body-sm text-surface-fg placeholder:text-surface-fg-muted focus:outline-none focus:ring-2 focus:ring-primary-500"
            />
          </div>
          <div className="space-y-1.5">
            <label htmlFor="theme-color" className="block text-body-sm font-medium">
              Theme color
            </label>
            <div className="flex items-center gap-2">
              <input
                id="theme-color"
                type="color"
                value={themeColor}
                onChange={(e) => setThemeColor(e.target.value)}
                className="h-10 w-12 cursor-pointer rounded-md border border-surface-border bg-surface-1 p-1 focus:outline-none focus:ring-2 focus:ring-primary-500"
              />
              <span className="font-mono text-body-sm text-surface-fg">{themeColor}</span>
            </div>
          </div>
        </div>
      </div>

      {/* Download button */}
      <Button
        onClick={handleDownload}
        disabled={busy || !sourceFile}
        className="w-full sm:w-auto"
      >
        <Download className="mr-2 size-4" aria-hidden />
        {busy ? "Generating…" : "Download ZIP"}
      </Button>
    </div>
  );
}
