import {
  Archive,
  BarChart2,
  Binary,
  Blend,
  BookOpen,
  Camera,
  Calculator,
  ClipboardList,
  Code2,
  Combine,
  Contrast,
  Crop,
  EyeOff,
  FileArchive,
  FileImage,
  FileMinus,
  FileText,
  FileX,
  FlipHorizontal2,
  Gauge,
  FilePen,
  FoldVertical,
  FormInput,
  Hash,
  Home,
  IdCard,
  Image,
  Landmark,
  LayoutGrid,
  Link,
  LockOpen,
  Maximize2,
  MessageSquare,
  Monitor,
  Palette,
  PenLine,
  Pipette,
  Printer,
  QrCode,
  Receipt,
  RectangleHorizontal,
  Repeat,
  RotateCw,
  Ruler,
  ScanLine,
  ScanSearch,
  ScanText,
  Scissors,
  Send,
  Share2,
  Shrink,
  Sigma,
  Signature,
  Sliders,
  Sparkles,
  Stamp,
  SquareSlash,
  Square,
  Sticker,
  Sunrise,
  Swords,
  Images,
  Layers,
  Lock,
  Package,
  Type,
  UserCheck,
  Video,
  Wallet,
  Droplets,
  type LucideIcon,
} from "lucide-react";
import type { ToolIconKind } from "@/lib/tools";

const COLOR_CLASSES: Record<string, string> = {
  accent: "bg-accent-3 text-accent-11",
  info: "bg-info-3 text-info-11",
  success: "bg-success-3 text-success-11",
  warning: "bg-warning-3 text-warning-11",
  error: "bg-error-3 text-error-11",
  neutral: "bg-neutral-3 text-neutral-11",
};

const SIZE_CLASSES = {
  sm: "h-8 w-8 rounded-md",
  md: "h-12 w-12 rounded-lg",
  lg: "h-16 w-16 rounded-xl",
} as const;

const ICON_PX = { sm: 18, md: 26, lg: 32 } as const;

const ICONS: Record<ToolIconKind, LucideIcon> = {
  "photo-resize": Crop,
  "image-compress": Gauge,
  "video-compress": Video,
  "document-photo": IdCard,
  "photo-signature-joiner": PenLine,
  "print-sheet": Printer,
  "jpg-to-pdf": FileText,
  "quick-send": Send,
  "pdf-compress": FileArchive,
  "pdf-merge-split": Combine,
  "print-job-slip": ClipboardList,
  "image-format-convert": Repeat,
  "qr-generate": QrCode,
  "qr-scan": ScanLine,
  "heic-to-jpg": FileImage,
  "photo-grayscale": Contrast,
  "aadhaar-collage": Layers,
  "image-to-text": ScanText,
  "pdf-to-jpg": Images,
  "pdf-rotate": RotateCw,
  "signature-maker": Signature,
  "image-crop": Scissors,
  "image-rotate": FlipHorizontal2,
  "bg-remove": Sparkles,
  "batch-compress": Package,
  "aadhaar-mask": EyeOff,
  "pdf-password": Lock,
  "pdf-page-manager": LayoutGrid,
  "pdf-page-numbers": Hash,
  "pdf-watermark": Stamp,
  "pdf-redact": SquareSlash,
  "pdf-sign": FilePen,
  "pdf-unlock": LockOpen,
  "pdf-crop": Shrink,
  "pdf-flatten": FoldVertical,
  "pdf-ocr": ScanSearch,
  "scan-to-pdf": Camera,
  "pdf-form-filler": FormInput,
  "image-watermark": Droplets,
  "image-resize": Maximize2,
  "text-to-pdf": Type,
  "pdf-repair": FileX,
  "gst-invoice": Receipt,
  "salary-slip": Wallet,
  "affidavit": UserCheck,
  "rent-agreement": Home,
  "zip-tool": Archive,
  "pdf-to-images": Images,
  "pdf-metadata": FileMinus,
  "image-to-base64": Binary,
  "image-color-picker": Pipette,
  "experience-letter": BookOpen,
  "noc-generator": MessageSquare,
  "bonafide-certificate": Landmark,
  "cheque-print": Calculator,
  "emi-calculator": Calculator,
  "unit-converter": Ruler,
  "word-counter": Sigma,
  "barcode-generator": BarChart2,
  "svg-to-png": Image,
  "svg-viewer": Code2,
  "contrast-checker": Swords,
  "color-convert": Blend,
  "color-palette": Palette,
  "palette-builder": Sliders,
  "gradient-maker": Sunrise,
  "shadow-maker": Square,
  "border-radius-tool": RectangleHorizontal,
  "favicon-maker": Sticker,
  "social-image-resize": Share2,
  "placeholder-img": Monitor,
  "css-unit-converter": Sigma,
  "business-card-maker": Link,
};

export function ToolIcon({
  kind,
  color,
  size = "md",
}: {
  kind: ToolIconKind;
  color: keyof typeof COLOR_CLASSES;
  size?: keyof typeof SIZE_CLASSES;
}) {
  const Icon = ICONS[kind];
  return (
    <div
      className={`${COLOR_CLASSES[color]} ${SIZE_CLASSES[size]} inline-flex items-center justify-center`}
    >
      <Icon size={ICON_PX[size]} strokeWidth={1.75} aria-hidden />
    </div>
  );
}
